// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UiZIn4csUxUT-_RMOW7TuJgAmcrQzdY',
    appId: '1:971909267222:web:1653876c1a95fa03ba1a37',
    messagingSenderId: '971909267222',
    projectId: 'elrincondejuan-ac71b',
    authDomain: 'elrincondejuan-ac71b.firebaseapp.com',
    storageBucket: 'elrincondejuan-ac71b.firebasestorage.app',
    measurementId: 'G-RC4SRPZ098',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLmoy5GKi3_2l56YCoQsm8m9A_KMt--sQ',
    appId: '1:971909267222:ios:1ae58c854646b789ba1a37',
    messagingSenderId: '971909267222',
    projectId: 'elrincondejuan-ac71b',
    storageBucket: 'elrincondejuan-ac71b.firebasestorage.app',
    iosBundleId: 'com.example.gestionPropinas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLmoy5GKi3_2l56YCoQsm8m9A_KMt--sQ',
    appId: '1:971909267222:ios:1ae58c854646b789ba1a37',
    messagingSenderId: '971909267222',
    projectId: 'elrincondejuan-ac71b',
    storageBucket: 'elrincondejuan-ac71b.firebasestorage.app',
    iosBundleId: 'com.example.gestionPropinas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-UiZIn4csUxUT-_RMOW7TuJgAmcrQzdY',
    appId: '1:971909267222:web:c141066e69fba4baba1a37',
    messagingSenderId: '971909267222',
    projectId: 'elrincondejuan-ac71b',
    authDomain: 'elrincondejuan-ac71b.firebaseapp.com',
    storageBucket: 'elrincondejuan-ac71b.firebasestorage.app',
    measurementId: 'G-FVHTYR7VBV',
  );

}